# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_geral/design_geral.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral || ORIG_REF_NAME==design_geral} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_processing_system7_0_0/design_geral_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_processing_system7_0_0 || ORIG_REF_NAME==design_geral_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_scheduler_0_0/design_geral_scheduler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_scheduler_0_0 || ORIG_REF_NAME==design_geral_scheduler_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_itemlist/mem_itemlist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_itemlist || ORIG_REF_NAME==mem_itemlist} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_commandlist/mem_commandlist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_commandlist || ORIG_REF_NAME==mem_commandlist} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_prioritylist/mem_prioritylist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_prioritylist || ORIG_REF_NAME==mem_prioritylist} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_delaylist/mem_delaylist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_delaylist || ORIG_REF_NAME==mem_delaylist} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_xlconstant_0_0/design_geral_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_xlconstant_0_0 || ORIG_REF_NAME==design_geral_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_ps7_0_axi_periph_0/design_geral_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_geral_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_rst_ps7_0_100M_0/design_geral_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_geral_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_xlconstant_1_0/design_geral_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_xlconstant_1_0 || ORIG_REF_NAME==design_geral_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_axi_timer_0_0/design_geral_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_axi_timer_0_0 || ORIG_REF_NAME==design_geral_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_xlconcat_0_0/design_geral_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_xlconcat_0_0 || ORIG_REF_NAME==design_geral_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_c_counter_binary_0_0/design_geral_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_c_counter_binary_0_0 || ORIG_REF_NAME==design_geral_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_xbar_0/design_geral_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_xbar_0 || ORIG_REF_NAME==design_geral_xbar_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_timers_ip_0_0/design_geral_timers_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_timers_ip_0_0 || ORIG_REF_NAME==design_geral_timers_ip_0_0} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_timers_ip_0_0/src/mem_timers/mem_timers.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_timers || ORIG_REF_NAME==mem_timers} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_timers_ip_0_0/src/mem_info/mem_info.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_info || ORIG_REF_NAME==mem_info} -quiet] -quiet

# IP: bd/design_geral/ip/design_geral_auto_pc_0/design_geral_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_geral_auto_pc_0 || ORIG_REF_NAME==design_geral_auto_pc_0} -quiet] -quiet

# XDC: bd/design_geral/ip/design_geral_processing_system7_0_0/design_geral_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_geral_processing_system7_0_0 || ORIG_REF_NAME==design_geral_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_itemlist/mem_itemlist_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_commandlist/mem_commandlist_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_prioritylist/mem_prioritylist_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_scheduler_0_0/src/mem_delaylist/mem_delaylist_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_rst_ps7_0_100M_0/design_geral_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_geral_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_geral_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_geral/ip/design_geral_rst_ps7_0_100M_0/design_geral_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_geral_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_geral_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_geral/ip/design_geral_axi_timer_0_0/design_geral_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_geral_axi_timer_0_0 || ORIG_REF_NAME==design_geral_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_geral/ip/design_geral_axi_timer_0_0/design_geral_axi_timer_0_0_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_c_counter_binary_0_0/design_geral_c_counter_binary_0_0_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_xbar_0/design_geral_xbar_0_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_timers_ip_0_0/src/mem_timers/mem_timers_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_timers_ip_0_0/src/mem_info/mem_info_ooc.xdc

# XDC: bd/design_geral/ip/design_geral_auto_pc_0/design_geral_auto_pc_0_ooc.xdc

# XDC: bd/design_geral/design_geral_ooc.xdc
