webtalk_init -webtalk_dir C:\\Users\\sergiopereira\\Vivado_projects\\RTOS_codesign\\projects\\project_srtos\\project_srtos.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-07-13 03:38:14" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211311721_0_0_063" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s14a4svtof7h3qnbkeon6lp85n" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.055 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1531440580621" -context "sdk\\\\bsp/1531440580621"
webtalk_add_data -client sdk -key hwid -value "1531240385675" -context "sdk\\\\bsp/1531440580621"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1531440580621"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1531440580621"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1531440580621"
webtalk_add_data -client sdk -key uid -value "1531445546734" -context "sdk\\\\bsp/1531445546734"
webtalk_add_data -client sdk -key hwid -value "1531240385675" -context "sdk\\\\bsp/1531445546734"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1531445546734"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1531445546734"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1531445546734"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key DebugCount -value "13" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1531449494938"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1531449494938"
webtalk_transmit -clientid 2618478459 -regid "211311721_0_0_063" -xml C:\\Users\\sergiopereira\\Vivado_projects\\RTOS_codesign\\projects\\project_srtos\\project_srtos.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\sergiopereira\\Vivado_projects\\RTOS_codesign\\projects\\project_srtos\\project_srtos.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\sergiopereira\\Vivado_projects\\RTOS_codesign\\projects\\project_srtos\\project_srtos.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
