# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_rtos/design_rtos.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos || ORIG_REF_NAME==design_rtos} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_processing_system7_0_0/design_rtos_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_processing_system7_0_0 || ORIG_REF_NAME==design_rtos_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_scheduler_0_0/design_rtos_scheduler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_scheduler_0_0 || ORIG_REF_NAME==design_rtos_scheduler_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_itemlist/mem_itemlist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_itemlist || ORIG_REF_NAME==mem_itemlist} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_commandlist/mem_commandlist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_commandlist || ORIG_REF_NAME==mem_commandlist} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_prioritylist/mem_prioritylist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_prioritylist || ORIG_REF_NAME==mem_prioritylist} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_delaylist/mem_delaylist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mem_delaylist || ORIG_REF_NAME==mem_delaylist} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_ps7_0_axi_periph_0/design_rtos_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_rtos_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_rst_ps7_0_100M_0/design_rtos_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_rtos_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_axi_timer_0_0/design_rtos_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_axi_timer_0_0 || ORIG_REF_NAME==design_rtos_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_xlconcat_0_0/design_rtos_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_xlconcat_0_0 || ORIG_REF_NAME==design_rtos_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_c_counter_binary_0_0/design_rtos_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_c_counter_binary_0_0 || ORIG_REF_NAME==design_rtos_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_xbar_0/design_rtos_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_xbar_0 || ORIG_REF_NAME==design_rtos_xbar_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_xlconstant_0_0/design_rtos_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_xlconstant_0_0 || ORIG_REF_NAME==design_rtos_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_xlconstant_0_1/design_rtos_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_xlconstant_0_1 || ORIG_REF_NAME==design_rtos_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_rtos/ip/design_rtos_auto_pc_0/design_rtos_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rtos_auto_pc_0 || ORIG_REF_NAME==design_rtos_auto_pc_0} -quiet] -quiet

# XDC: bd/design_rtos/ip/design_rtos_processing_system7_0_0/design_rtos_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_rtos_processing_system7_0_0 || ORIG_REF_NAME==design_rtos_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_itemlist/mem_itemlist_ooc.xdc

# XDC: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_commandlist/mem_commandlist_ooc.xdc

# XDC: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_prioritylist/mem_prioritylist_ooc.xdc

# XDC: bd/design_rtos/ip/design_rtos_scheduler_0_0/src/mem_delaylist/mem_delaylist_ooc.xdc

# XDC: bd/design_rtos/ip/design_rtos_rst_ps7_0_100M_0/design_rtos_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_rtos_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_rtos_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_rtos/ip/design_rtos_rst_ps7_0_100M_0/design_rtos_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_rtos_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_rtos_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_rtos/ip/design_rtos_axi_timer_0_0/design_rtos_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_rtos_axi_timer_0_0 || ORIG_REF_NAME==design_rtos_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_rtos/ip/design_rtos_axi_timer_0_0/design_rtos_axi_timer_0_0_ooc.xdc

# XDC: bd/design_rtos/ip/design_rtos_auto_pc_0/design_rtos_auto_pc_0_ooc.xdc

# XDC: bd/design_rtos/design_rtos_ooc.xdc
